spring:
    data:
        mongodb:
            uri: mongodb+srv://thalesCastellani:Mazingers1*@cluster0.izc8v.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
            database: superheroapi